In [6]:
import numpy as np
# Define matrices A and B
A = np.array([[2, -1], [0, 3]])
B = np.array([[1, 4], [-2, 5]])
# Define scalars c and d
c = 2
d = 3
# a. Compute (cA), (dB), and (c + d)A
cA = c * A
dB = d * B
cdA = (c + d) * A
print("cA:")
print(cA)
print("\ndB:")
print(dB)
print("\n(c + d)A:")
print(cdA)


cA:
[[ 4 -2]
 [ 0  6]]

dB:
[[ 3 12]
 [-6 15]]

(c + d)A:
[[10 -5]
 [ 0 15]]


In [10]:
# b. Verify Scalar Multiplication Properties
# Checking if cA + dA = (c + d)A
print("\nVerifying cA + dA = (c + d)A:")
print(np.allclose(cA + dB, (c + d) * A))  
print(np.allclose(c*A + d*A, (c + d)*A))  










Verifying cA + dA = (c + d)A:
False
True


In [8]:
# c. Find the transpose of both matrices
A_T = A.T
B_T = B.T
print("\nTranspose of A:")
print(A_T)
print("\nTranspose of B:")
print(B_T)


Transpose of A:
[[ 2  0]
 [-1  3]]

Transpose of B:
[[ 1 -2]
 [ 4  5]]


In [9]:
# d. Check if A and B are invertible and find inverses
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
print(f"\nDeterminant of A: {det_A}")
print(f"Determinant of B: {det_B}")
if det_A != 0:
    A_inv = np.linalg.inv(A)
    print("\nInverse of A:")
    print(A_inv)
else:
    print("\nA is not invertible.")
if det_B != 0:
    B_inv = np.linalg.inv(B)
    print("\nInverse of B:")
    print(B_inv)
else:
    print("\nB is not invertible.")









Determinant of A: 6.0
Determinant of B: 13.0

Inverse of A:
[[0.5        0.16666667]
 [0.         0.33333333]]

Inverse of B:
[[ 0.38461538 -0.30769231]
 [ 0.15384615  0.07692308]]
