# Task 4 Case Study Solution

In [ ]:
# From the problem, we have 4 students × 3 subjects (Math, English, Science).
# This is a matrix with rows = students, columns = subjects. 
# so we have 4 rows and 3 columns.
import numpy as np

# Representing Data as a Matrix
scores = np.array([
    [80, 70, 90],   # Student 1
    [60, 85, 75],   # Student 2
    [95, 88, 92],   # Student 3
    [70, 60, 65]    # Student 4
])
print("Scores Matrix:\n", scores)

Scores Matrix:
 [[80 70 90]
 [60 85 75]
 [95 88 92]
 [70 60 65]]


In [ ]:
# Calculate Total Scores per Student (Vector Addition)
# Each student’s total score = sum of their row vector.
# In Linear Algebra, that means summing across the row dimension.
total_scores = np.sum(scores, axis=1)
print("\nTotal Scores per Student:", total_scores)


Total Scores per Student: [240 220 275 195]


In [ ]:
# Applying the Weights (Math is twice as important as others)
# Suppose Math is twice as important → multiply Math column by 2.
# In Linear Algebra, this is element-wise scalar multiplication.
weights_scalar = np.array([2, 1, 1])  # Math ×2
weighted_scores = scores * weights_scalar
weighted_totals = np.sum(weighted_scores, axis=1)
print("\nWeighted Scores Matrix:\n", weighted_scores)
print("Weighted Totals per Student:", weighted_totals)


Weighted Scores Matrix:
 [[160  70  90]
 [120  85  75]
 [190  88  92]
 [140  60  65]]
Weighted Totals per Student: [320 280 370 265]


In [ ]:
# The Average Score per Subject (Matrix Operations)
# Now, instead of rows, we want averages per subject (column).
# That’s just the column mean.
avg_per_subject = np.mean(scores, axis=0)
print("\nAverage Score per Subject:", avg_per_subject)


Average Score per Subject: [76.25 75.75 80.5 ]


In [18]:
# The Final Grades using Matrix Multiplication
# Using the weights: [0.5, 0.3, 0.2].
# This is a dot product between each student’s score vector and the weights.
# In Linear Algebra, that’s matrix × vector multiplication.
weight_vector = np.array([0.5, 0.3, 0.2])  # Math=50%, English=30%, Science=20%
final_grades = scores @ weight_vector
print("\nFinal Grades:", final_grades)


Final Grades: [79.  70.5 92.3 66. ]


In [19]:
# Comparison of the  Students (Vector Subtraction)
# To compare Student 3 and Student 4, we subtract their vectors.
# In Linear Algebra, subtraction tells us the difference in each subject.
comparison = scores[2] - scores[3]  # Student 3 - Student 4
print("\nComparison between Student 3 and Student 4 (Math, English, Science):", comparison)


Comparison between Student 3 and Student 4 (Math, English, Science): [25 28 27]
